version: '2.2'

x-logging: &default-logging
  driver: 'splunk'
  options:
    splunk-token: '11111111-1111-1111-1111-1111111111113'
    splunk-url: 'https://localhost:18088'
    splunk-insecureskipverify: 'true'
    splunk-verify-connection: 'false'
    splunk-format: 'json'
    tag: '{{.Name}}-{{.ID}}'

networks:
  buffinet-pow:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.1
  buffinet-poa:
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24
          gateway: 172.28.2.1
  splunk:
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.0/24
          gateway: 172.28.3.1

services:
  splunk.example.com:
    container_name: splunk.example.com
    image: splunk/splunk:7.2.3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    networks:
      - buffinet-poa
      - buffinet-pow
      - splunk
    ports:
      - '18000:8000'
      - '18088:8088'
    volumes:
      - ./splunk-apps/chainmon:/opt/splunk/etc/apps/chainmon:rw
      - ./splunk-apps/ethereum_monitoring:/opt/splunk/etc/apps/ethereum_monitoring:rw
      - ./splunk-apps/metrics_explorer:/opt/splunk/etc/apps/metrics_explorer:rw
      - ./splunk-apps/splunk-for-hyperledger-fabric:/opt/splunk/etc/apps/splunk-for-hyperledger-fabric:rw
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 5s
      timeout: 5s
      retries: 20

  pow.bootnode.example.com:
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffinet-pow:
        ipv4_address: 172.28.1.100
        aliases:
          - powbootnode
    entrypoint: /root/init.sh
    command: 'secret@splunk.example.com:9001 --nodekeyhex fb375414f31b25b61aa70bb33f356a7ebaf61983883274980aab9c3b92af6e82 --datadir="/root/.ethereum" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=59206 --rpc --rpcaddr="0.0.0.0" --syncmode "full" --mine --minerthreads 1'
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/pow.json:/root/genesis.json
      - ./files/init.sh:/root/init.sh
      - ./files/password:/root/password
    logging: *default-logging
    depends_on:
      splunk.example.com:
        condition: service_healthy
    ports:
      - '8545:8545'
      - '8546:8546'

  pow.example.com:
    scale: 1
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffinet-pow:
        aliases:
          - pow
    entrypoint: /root/init.sh
    command: 'secret@splunk.example.com:9001 --bootnodes="enode://fd542531647920bd370182731e94df6a744b11031e93956f9912e8863b239f91e40387cae46aac37f36b71ec1e119c2ce8a45a447650cfc96489ab6633b6bf51@172.28.1.100:30303" --datadir="/root/.ethereum" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=59206 --rpc --rpcaddr="0.0.0.0" --ws --wsaddr="0.0.0.0" --wsorigins "*" --miner.etherbase="0x69eff55dce156926164e276ed03484672ec84fbb" --unlock "0x69eff55dce156926164e276ed03484672ec84fbb" --mine --minerthreads 1 --password "/root/password" --syncmode "full"'
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/pow.json:/root/genesis.json
      - ./files/init.sh:/root/init.sh
      - ./files/password:/root//password
      - ./files/static-nodes-pow.json:/root/.ethereum/static-nodes.json
    logging: *default-logging
    depends_on:
      splunk.example.com:
        condition: service_healthy
      pow.bootnode.example.com:
        condition: service_started

  eth-logger-pow:
    build:
      context: ./ethlogger
    restart: on-failure
    networks:
      - buffinet-pow
    volumes:
      - ./abi:/app/abi
    environment:
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-111111111111
      - SPLUNK_HOST=splunk.example.com
      - SPLUNK_PORT=8088
      - GETH_WS_HOST=pow
      - GETH_WS_PORT=8546
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging

  poa.bootnode.example.com:
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffinet-poa:
        ipv4_address: 172.28.2.100
        aliases:
          - poabootnode
    entrypoint: /root/init.sh
    command: 'secret@splunk.example.com:9002 --nodekeyhex fb375414f31b25b61aa70bb33f356a7ebaf61983883274980aab9c3b92af6e82 --datadir=/root/.ethereum --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=53324 --rpc --rpcaddr="0.0.0.0" --miner.etherbase="0x69eff55dce156926164e276ed03484672ec84fbb" --unlock "0x69eff55dce156926164e276ed03484672ec84fbb" --mine --password "/root/password" --syncmode "full"'
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/poa.json:/root/genesis.json
      - ./files/init.sh:/root/init.sh
      - ./files/password:/root/password
    logging: *default-logging
    depends_on:
      splunk.example.com:
        condition: service_healthy
    ports:
      - '9545:8545'
      - '9546:8546'
      

  poa.example.com:
    scale: 2
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffinet-poa:
        aliases:
          - poa
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/poa.json:/root/genesis.json
      - ./files/password:/root/password
      - ./files/init.sh:/root/init.sh
      - ./files/static-nodes.json:/root/.ethereum/static-nodes.json
    entrypoint: /root/init.sh
    logging: *default-logging
    command: 'secret@splunk.example.com:9002 --bootnodes="enode://fd542531647920bd370182731e94df6a744b11031e93956f9912e8863b239f91e40387cae46aac37f36b71ec1e119c2ce8a45a447650cfc96489ab6633b6bf51@172.28.2.100:30303" --datadir="/root/.ethereum" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=53324 --rpc --rpcaddr="0.0.0.0" --ws --wsaddr="0.0.0.0" --wsorigins "*" --miner.etherbase="0x69eff55dce156926164e276ed03484672ec84fbb" --unlock "0x69eff55dce156926164e276ed03484672ec84fbb" --mine --password "/root/password" --syncmode "full"'
    depends_on:
      splunk.example.com:
        condition: service_healthy
      poa.bootnode.example.com:
        condition: service_started

  eth-logger-poa:
    build:
      context: ./ethlogger
    restart: on-failure
    networks:
      - buffinet-poa
    volumes:
      - ./abi:/app/abi
    environment:
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-111111111112
      - SPLUNK_HOST=splunk.example.com
      - SPLUNK_PORT=8088
      - GETH_WS_HOST=poa
      - GETH_WS_PORT=8546
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging

  cadivsor.example.com:
    container_name: cadvisor.example.com
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --storage_driver=statsd
      - --storage_driver_host=splunk.example.com:8125
      - --storage_driver_db=docker
      - --docker_only=true
      - --enable_load_reader=true
    networks:
      - splunk
    user: root
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging
