version: '2.1'

x-logging:
  &default-logging
  driver: "splunk"
  options:
    splunk-token: "11111111-1111-1111-1111-1111111111113"
    splunk-url: "https://localhost:18088"
    splunk-insecureskipverify: "true"
    splunk-verify-connection: "false"
    splunk-format: "json"
    tag: "{{.Name}}-{{.ID}}"

networks:
  buffi-poa:
  buffi-pow:
  splunk:

services:
  splunk.example.com:
    container_name: splunk.example.com
    image: splunk/splunk:7.2.3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    networks:
      - buffi-poa
      - buffi-pow
      - splunk
    ports:
      - "18000:8000"
      - "18088:8088"
    volumes:
      - ./splunk-apps/container-inputs:/opt/splunk/etc/apps/container-inputs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  pow.example.com:
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffi-pow:
        aliases:
          - pow
    entrypoint: /root/init.sh
    command: '--datadir=~/.ethereum --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=59206 --rpc --rpcaddr="0.0.0.0" --ws --wsaddr="0.0.0.0" --wsorigins "*" --miner.etherbase="0x69eff55dce156926164e276ed03484672ec84fbb" --unlock "0x69eff55dce156926164e276ed03484672ec84fbb" --mine --password "/root/.ethereum/password" --ethstats ${HOSTNAME}:secret@splunk.example.com:9001'
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/poa.json:/root/.ethereum/genesis.json
      - ./files/init.sh:/root/init.sh
      - ./files/password:/root/.ethereum/password
    # ports:
    #   - "30303:30303"
    #   - "30303:30303/udp"
    #   - "8545:8545"
    logging: *default-logging
    depends_on:
      splunk.example.com:
        condition: service_healthy

  eth-logger-pow:
    image: dexa187/ethereum-logger
    restart: on-failure
    networks:
      - buffi-pow
    working_dir: /root/Ethereum-Logger
    environment:
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-111111111111
      - SPLUNK_HOST=splunk.example.com
      - SPLUNK_PORT=8088
      - GETH_WS_HOST=pow
      - GETH_WS_PORT=8546
    command: 'node app.js'
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging

  poa.example.com:
    image: ethereum/client-go
    restart: on-failure
    networks:
      buffi-poa:
        aliases:
          - poa
    volumes:
      - ./files/keystore:/root/.ethereum/keystore
      - ./files/poa.json:/root/.ethereum/genesis.json
      - ./files/password:/root/.ethereum/password
      - ./files/init.sh:/root/init.sh
    entrypoint: /root/init.sh
    command: '--datadir=~/.ethereum --rpccorsdomain="*" --rpcapi "db,personal,eth,net,web3" --networkid=53324 --rpc --rpcaddr="0.0.0.0" --ws --wsaddr="0.0.0.0" --wsorigins "*" --miner.etherbase="0x69eff55dce156926164e276ed03484672ec84fbb" --unlock "0x69eff55dce156926164e276ed03484672ec84fbb" --mine --password "/root/.ethereum/password" --ethstats ${HOSTNAME}:secret@splunk.example.com:9001'
    logging: *default-logging
    depends_on:
      splunk.example.com:
        condition: service_healthy

  eth-logger-poa:
    image: dexa187/ethereum-logger
    restart: on-failure
    networks:
      - buffi-poa
    working_dir: /root/Ethereum-Logger
    environment:
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-111111111112
      - SPLUNK_HOST=splunk.example.com
      - SPLUNK_PORT=8088
      - GETH_WS_HOST=poa
      - GETH_WS_PORT=8546
    command: 'node app.js'
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging

  cadivsor.example.com:
    container_name: cadvisor.example.com
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --storage_driver=statsd
      - --storage_driver_host=splunk.example.com:8125
      - --storage_driver_db=docker
      - --docker_only=true
      - --enable_load_reader=true
    networks:
      - splunk
    user: root
    depends_on:
      splunk.example.com:
        condition: service_healthy
    logging: *default-logging

